#pragma once

#include <iostream>
#include <memory>
#include <utility>
#include <algorithm>
#include <functional>
#include <ctime>
#include <cstdlib>
#include <typeinfo>
#include <string>
#include <sstream>
#include <array>
#include <vector>
#include <deque>
#include <queue>
#include <map>
#include <unordered_map>
#include <unordered_set>
#include <chrono>
#include <bitset>